### ISSUE TITLE
Ensure POSTs have a size limit and a request rate limit

### ISSUE THREAD

**Issue by wresuolc** [mozilla/speech-proxy#5]
I think these can be set in nginx, so I'm ccing @jasonthomas

I don't have recommendations for values here.

**Comment by wresuolc** [comment]
@andrenatal will get a value for max size limit

@jvehent does the IP reputation service do rate limiting?  I don't think we have anything built around that in ops

**Comment by jbuck** [comment]
We could also use AWS WAF if we need something quick: https://aws.amazon.com/about-aws/whats-new/2017/06/aws-announces-rate-based-rules-for-aws-waf/

**Comment by jvehent** [comment]
> @jvehent does the IP reputation service do rate limiting? I don't think we have anything built around that in ops

Not directly. It's meant to blacklist abusive IPs, some of which could be violating rate limits. But we're not ready to use it yet, so I would leave rate limiting aside for launch.

POST size limit should be easy to implement in nginx. I don't see the need for the AWS WAF since we already have a complex request processing stack (nginx) in front of the app, but it's up to ops.

**Comment by milescrabill** [comment]
I threw a hard cap of 20mb in. Should we lower it?

**Comment by andrenatal** [comment]
@miles, yes, much lower. I did some testing here and 500k should suffice.

**Comment by milescrabill** [comment]
This is done
